In [8]:
!pip install numpy pandas scikit-learn matplotlib seaborn

Requirement already satisfied: numpy in c:\users\cholo\anaconda3\lib\site-packages (1.26.4)
Requirement already satisfied: pandas in c:\users\cholo\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: scikit-learn in c:\users\cholo\anaconda3\lib\site-packages (1.5.1)
Requirement already satisfied: matplotlib in c:\users\cholo\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: seaborn in c:\users\cholo\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\cholo\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\cholo\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\cholo\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: scipy>=1.6.0 in c:\users\cholo\anaconda3\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\cholo\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\cholo\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\cholo\anaconda3\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\cholo\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\cholo\anaconda3\lib\site-packages (from matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\cholo\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\cholo\anaconda3\lib\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\cholo\anaconda3\lib\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\cholo\anaconda3\lib\site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: six>=1.5 in c:\users\cholo\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [9]:
import numpy as np
import pandas as pd

df = pd.read_csv('./auto-mpg.csv', header=0, engine='python')

In [10]:
df.tail(7)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
391,36.0,4,135.0,84,2370,13.0,82,1,dodge charger 2.2
392,27.0,4,151.0,90,2950,17.3,82,1,chevrolet camaro
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [11]:
df.shape

(398, 9)

In [12]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'car_name'],
      dtype='object')

In [24]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car_name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 67.2 KB

In [16]:
df['horsepower'].unique()

array(['130', '165', '150', '140', '198', '220', '215', '225', '190',
       '170', '160', '95', '97', '85', '88', '46', '87', '90', '113',
       '200', '210', '193', '?', '100', '105', '175', '153', '180', '110',
       '72', '86', '70', '76', '65', '69', '60', '80', '54', '208', '155',
       '112', '92', '145', '137', '158', '167', '94', '107', '230', '49',
       '75', '91', '122', '67', '83', '78', '52', '61', '93', '148',
       '129', '96', '71', '98', '115', '53', '81', '79', '120', '152',
       '102', '108', '68', '58', '149', '89', '63', '48', '66', '139',
       '103', '125', '133', '138', '135', '142', '77', '62', '132', '84',
       '64', '74', '116', '82'], dtype=object)

In [18]:
df['horsepower']=='?'

0      False
1      False
2      False
3      False
4      False
       ...
393    False
394    False
395    False
396    False
397    False
Name: horsepower, Length: 398, dtype: bool

In [15]:
print(df.columns)

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'car_name'],
      dtype='object')

In [19]:
df_cyl_6 = [df['cylinders']==6]

In [21]:
df_cyl_4 = [df['cylinders']==4]

In [30]:
df_cyl_6.info()

AttributeError: 'list' object has no attribute 'info'

In [29]:
df[df['horsepower']=='?']

Empty DataFrame
Columns: [mpg, cylinders, displacement, horsepower, weight, acceleration, model_year, origin, car_name]
Index: []

In [23]:
print(' 데이터셋 크기 : ', df.shape)

df.head()

 데이터셋 크기 :  (398, 9)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [25]:
df.isnull().sum(1)  # 결측치 데이터 확인(행별)
df.isnull().sum()  # 결측치 데이터 확인(열별)

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
car_name        0
dtype: int64

In [26]:
df.isnull().sum().sum() # 결측치 데이터 확인(전체)

0

In [27]:
df['horsepower'].replace('?', np.nan, inplace=True)      # '?' -> np.nan 변경
df.dropna(subset=['horsepower'], axis=0, inplace=True)   # 결측치 행을 삭제
df['horsepower'] = df['horsepower'].astype('float')      # 문자열 -> 실수형 변환

C:\Users\cholo\AppData\Local\Temp\ipykernel_3724\2999005857.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].replace('?', np.nan, inplace=True)      # '?' -> np.nan 변경

In [31]:
df['horsepower'].replace('?', np.nan)

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...
393     86.0
394     52.0
395     84.0
396     79.0
397     82.0
Name: horsepower, Length: 392, dtype: float64

In [35]:
df_filter = df.drop(['car_name', 'origin', 'horsepower', 'mpg'], axis=1, inplace=False)  # 분석하지 않을 변수 제외

In [34]:
kpl = 1.60934 / 3.78541
df['kpl'] = df['mpg'] * kpl
df['kpl'] = df['kpl'].round(2) # 소수점 둘째 자리에서 반올림

In [43]:
df[['mpg']]

      mpg
0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
..    ...
393  27.0
394  44.0
395  32.0
396  28.0
397  31.0

[392 rows x 1 columns]

In [46]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name,kpl
0,18.0,8,307.0,130.0,3504,12.0,70,1,chevrolet chevelle malibu,7.65
1,15.0,8,350.0,165.0,3693,11.5,70,1,buick skylark 320,6.38
2,18.0,8,318.0,150.0,3436,11.0,70,1,plymouth satellite,7.65
3,16.0,8,304.0,150.0,3433,12.0,70,1,amc rebel sst,6.80
4,17.0,8,302.0,140.0,3449,10.5,70,1,ford torino,7.23
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,1,ford mustang gl,11.48
394,44.0,4,97.0,52.0,2130,24.6,82,2,vw pickup,18.71
395,32.0,4,135.0,84.0,2295,11.6,82,1,dodge rampage,13.60
396,28.0,4,120.0,79.0,2625,18.6,82,1,ford ranger,11.90
397,31.0,4,119.0,82.0,2720,19.4,82,1,chevy s-10,13.18

In [45]:
X

     cylinders  displacement  weight  acceleration  model_year
0            8         307.0    3504          12.0          70
1            8         350.0    3693          11.5          70
2            8         318.0    3436          11.0          70
3            8         304.0    3433          12.0          70
4            8         302.0    3449          10.5          70
..         ...           ...     ...           ...         ...
393          4         140.0    2790          15.6          82
394          4          97.0    2130          24.6          82
395          4         135.0    2295          11.6          82
396          4         120.0    2625          18.6          82
397          4         119.0    2720          19.4          82

[392 rows x 5 columns]

In [36]:
print(' 데이터세트 크기 : ', df_filter.shape)
df_filter.head()
df_filter.info()

 데이터세트 크기 :  (392, 6)
<class 'pandas.core.frame.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cylinders     392 non-null    int64
 1   displacement  392 non-null    float64
 2   weight        392 non-null    int64
 3   acceleration  392 non-null    float64
 4   model_year    392 non-null    int64
 5   kpl           392 non-null    float64
dtypes: float64(3), int64(3)
memory usage: 21.4 KB

In [32]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [37]:
# X(독립변수/Input), Y(종속변수/Output) 분할
Y = df_filter['kpl']
X = df_filter.drop(['kpl'], axis=1, inplace=False)
display(X)
display(Y)

     cylinders  displacement  weight  acceleration  model_year
0            8         307.0    3504          12.0          70
1            8         350.0    3693          11.5          70
2            8         318.0    3436          11.0          70
3            8         304.0    3433          12.0          70
4            8         302.0    3449          10.5          70
..         ...           ...     ...           ...         ...
393          4         140.0    2790          15.6          82
394          4          97.0    2130          24.6          82
395          4         135.0    2295          11.6          82
396          4         120.0    2625          18.6          82
397          4         119.0    2720          19.4          82

[392 rows x 5 columns]

0       7.65
1       6.38
2       7.65
3       6.80
4       7.23
       ...
393    11.48
394    18.71
395    13.60
396    11.90
397    13.18
Name: kpl, Length: 392, dtype: float64

In [38]:
# 훈련용 데이터와 평가용 데이터 분할하기
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

In [39]:
# 선형회귀분석 : 모델 생성
lr = LinearRegression()

In [40]:
# 선형회귀분석 : 모델 훈련
lr.fit(X_train, Y_train)

LinearRegression()

In [41]:
# 선형회귀분석 : 평가 데이터에 대한 예측 수행 -> 예측 결과 Y_predict 구하기
Y_predict = lr.predict(X_test)

In [42]:
mse = mean_squared_error(Y_test, Y_predict)
rmse = np.sqrt(mse)

print('MSE : {0:.3f}, RMSE : {1:.3f}'.format(mse, rmse))
print('R^2(Variance score) : {0:.3f}'.format(r2_score(Y_test, Y_predict)))

MSE : 2.243, RMSE : 1.498
R^2(Variance score) : 0.798